README.md
Fix the link to point to the correct address. It was pointing relatively before.
=> Fix readme doc link

flexx/webruntime/chromeapp.py
I posted this on the issue tracker but I realized despite never having made a pull request before, I knew enough about git to figure it out so I made one.
The links to Chrome and Chromium on Linux are currently pointing to /usr/lib/google-chrome/google-chrome and /usr/lib/chromium-browser/chromium-browser.
The correct paths on modern distros to Chrome and Chromium are /usr/bin/google-chrome-$CHANNEL and /usr/bin/chromium respectively.
Tested on Arch Linux with Google Chrome stable channel.
closes #29
=> Fixed paths to Chrome and Chromium browsers on Linux

flexx/webruntime/common.py, flexx/webruntime/tests/test_runtimes.py, flexx/webruntime/xul.py
I changed a few of the assertions to use explicit errors in case of invalid input / checks.
I was using [Bandit](https://github.com/openstack/bandit) to check for potential vulnerabilities in a few popular Python projects and this came up as a warning:
```
>> Issue: Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
Severity: Low   Confidence: High
Location: flexx/webruntime/common.py:23
19	    """ Base class for all runtimes.
20	    """
21
22	    def __init__(self, **kwargs):
23	        assert 'url' in kwargs
24	        self._kwargs = kwargs
25	        self._proc = None
26	        self._streamreader = None
>> Issue: Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
Severity: Low   Confidence: …
```
=> Removed a few instances of asserts.

flexx/app/tornadoserver.py, flexx/react/pyscript.py, flexx/react/tests/test_both.py, flexx/ui/_widget.py
* Pong is also triggered when receiving other messages. This way, if the communication is very busy, the connection won't time out.
* Allow signals to be overloaded.
* Changing widget container triggers resize check.
=> a few small fixes

examples/ui/chatroom.py, flexx/app/session.py
* `session.status` is a bit easier, you can now check for it to evaluate to Falsy to determine if the connection is closed.
* Fixed leak in chatroom example
* Old pending sessions are cleared once in a while
I hope this fixes #62
=> Tweaks to avoid leaks

flexx/app/clientcore.py, flexx/app/tornadoserver.py, flexx/react/pyscript.py
When an error occurs while updating a signal (which is a common place where errors occur if you're writing new code), the report no includes a trace. Also made that the links in the trace are clickable in Firefox (Chrome already opens them in the dev console).
=> Improved support for debugging JS

flexx/app/assetstore.py, flexx/app/session.py, flexx/pyscript/stdlib.py, setup.cfg
Because you can get nasty bugs otherwise.
=> Prevent Model class name clashes

flexx/app/assetstore.py, flexx/ui/widgets/_label.py
Could not reset `user-select: none` for label widgets.
=> Change asset order to allow overriding Phosphor default styles

flexx/ui/_widget.py, flexx/ui/layouts/_box.py
Addendum to #90, using `height=100%`  caused problems. Just be a flexbox container if necessary.
=> better flexbox handling

flexx/ui/layouts/_box.py
In a flexbox, we should not try to use height, and width as much ...
See also #91 and #90
=> Fix flexbox (again)

flexx/app/tests/test_live.py
The live test was added during the legacy-py PR, but it kept stalling. Now attempt to make it work again, because it tests important code paths.
=> Enable live test on travis

flexx/ui/_widget.py
I am running uzbl, built with libjavascriptcoregtk-1.0-dev (2.4.11-1) . In this setup, the event attribute buttons is undefined whereas the attribute button exists. They both appear to have the same purpose in the context of mouse clicking.
=> Fallback on e.button if e.buttons is not available

flexx/pyscript/parser1.py, flexx/pyscript/tests/test_parser1.py
`foo = xx or []`  would yield `False` instead of `[]`, because of how the `truthy` function works. This PR makes the last entry in an OR be passed as is, and makes `truthy` wrap when an expression contains an or.
=> Pyscript improvement for using foo = x or y

docs/app/api.rst, flexx/app/__init__.py, flexx/app/examples/adding_handlers.py, flexx/app/examples/flexx_in_thread.py, flexx/app/funcs.py, flexx/app/tests/test_funcs.py, flexx/app/tests/test_live.py, flexx/app/tests/test_model.py, flexx/app/tornadoserver.py
Follow-up on #153 
This makes it possible to do:
```python
server = app.create_server(new_loop=True)
t = threading.Thread(target=app.start)
t.start()
```
Also renamed `app.get_current_thread()` -> `app.current_thread()`
cc @korijn @Maxyme
=> Add create_server(new_loop=True), and rename current_server

flexx/app/tests/test_live.py, flexx/app/tests/test_model.py, flexx/event/_emitters.py, flexx/event/_hasevents.py, flexx/event/_js.py, flexx/event/tests/test_both.py
Fixes #175 
This also makes some changes to the name of the underlying function for properties, emitters. Essentially, the underlying function needed to be stored under the actual name of the emitter for super() to work, and we made it work the same way for properties for consistency.
=> Make super work for emitters

flexx/app/assetstore.py, flexx/app/clientcore.py, flexx/app/funcs.py, flexx/app/session.py, flexx/app/tests/test_funcs.py, flexx/app/tornadoserver.py
Closes #140 
* The functions `app.serve(), app.launch(), app.export()` all have a similar API where the first arg is the Model class, the second a place to "put" it, and the third a dict of initial properties.
* For `serve()`, the second arg is a path to serve it on, which can be set to the empty string to serve it as the "main" app.
* App names in the url are case insensitive. If the url does not match the proper case, the page is redirected to the correct case.
* Refactored `MainHandler.get()` a bit.
=> Improvements to app.serve(), app.launch(), app.export()

flexx/app/session.py, flexx/app/tornadoserver.py, flexx/event/_handler.py, flexx/event/_hasevents.py, flexx/event/_js.py, flexx/event/tests/test_handlers.py, flexx/ui/examples/chatroom.py, flexx/ui/examples/colab_painting.py, flexx/ui/examples/monitor.py
This makes the handler store references of the objects of bound methods using a weak ref. That way, a handler can never be the thing that is holding back object deletion. In effect it is generally no longer necessary to disconnect connections; thinks should degenerate by themselves.
This is nice, since a typo in a disconnect call (as was present in the colabpainting example) could easily cause memory leaks (which is, I think, why the AWS server was broken so quickly).
Also allowed using decorators using `some_object.connect()`. In some examples, we can now write `relay.connect(...)`. By writing it in that way, the object is aware of the handler, and will dispose it when it is itself disposed, which means we don't get these 'cannot send commands, app is closed' warnings.
=> Improvements to avoid memory leaks

flexx/event/_handler.py, flexx/event/tests/test_handlers.py
E.g. `foo.connect('bar', print)` would not work anymore.
=> Fix that handler could no longer connect to builtin functions

flexx/app/funcs.py, flexx/ui/widgets/_group.py, flexx/ui/widgets/_slider.py
HTA is a format that is really just an .html file renamded to .hta, and one tag added. It's a bit of an old thing, and Edget does not support it. But its easy to add.
I was investigating this as a way to create native-looking desktop apps on Windows. Probably can work, but would not be a modern solution. But if we get a modern solution (e.g. based on UWP), we still might need HTA for older machines.
*Leaving these open, since HTA should only become a backend for `launch` if we have one that runs on Edge.` The question of which module should take care of exports is still a valid one, but we can address that when we add more export modes.*
=> Support for Windows HTA

flexx/app/model.py, flexx/event/__init__.py, flexx/event/_hasevents.py, flexx/event/examples/basic_emit.py, flexx/ui/examples/chatroom.py, flexx/ui/examples/colab_painting.py, flexx/ui/examples/monitor.py
Fixes #188 
There are two options when an event is connected that is not known:
* warn (as we do now)
* error
I think a warning suffices and is more backward compatible.
To do:
cc @korijn
=> Warn if handler connects to event that is not known

flexx/ui/_widget.py, flexx/ui/widgets/_canvas.py
Closes #174 
Based on the observation that preventing context menu etc. is mainly a concern for apps that make use of the canvas for user interaction, I've moved the preventdefault-logic to the canvas.
In theory someone could want extensive user interaction with html elements. in that case he/she can look at how its handled in the `Canvas` and apply that approach.
For now I've left open a way to invoke the context menu by holding down all 3 modifier keys. Let's see how that works out.
I did a bit of work on making capturing wheel events work in a nice way. I.e. allow the canvas to prevent page scrolling but not when the canvas just happens to "pass by"  during scrolling. I.e. for interactive apps in the notebook. Such apps should set the class attribute `CAPTURE_WHEEL` of the `Canvas` …
=> Prevent default event actions only for canvas

flexx/ui/_widget.py, flexx/ui/examples/deep.py, flexx/ui/examples/deep2.py
This bug has been in Flexx for a long time but only surfaced recently. Flexx already has a fix for a similar situation with a VBox in a VBox, but in this case it was a BoxPanel in a VBox.
cc @korijn
Needs a test/example.
=> Fix for boxpanel in vbox on chrome

flexx/webruntime/browser.py, flexx/webruntime/common.py
The problem was that when an app is launched in a browser, the subprocess that is spawned closes immediately (control is passed to a long-running firefox.exe/chrome.exe/etc.). Flexx detects this close and reported it as the webruntime shutting down.
=> webruntime: prevent error message when launching app in browser

flexx/ui/_widget.py, flexx/ui/examples/mondriaan.py
Implement #213 
The name "css_class_name" is a bit long, but I fear that "class_name" will confuse people. Maybe "css_name", or "style_name"? I'd also consider renaming "style" to sorta group these two props together.
=> Widget.css_class_name

flexx/app/clientcore.py, flexx/app/model.py, flexx/app/session.py, flexx/app/tests/test_model.py, flexx/app/tornadoserver.py, flexx/ui/_widget.py, flexx/ui/examples/stayin_alive.py
Fixes #141 (good enough)
* Adds a `keep_alive()` method to ~~`Model`~~ `Session`, which keeps an object alive for a period of time that is expressed in ping-roundtrips. This means that the object will always be around long enough to survive synchronisation jitter, even if Python or JS are busy for several seconds (or hours, really).
* The `keep_alive()` method is called upon Model creation, which means users won't have to think about it in a great deal of cases.
* This also improves the ping-pong mechanism to determine connection timeouts. You should now not get these "closed due to pong" errors if you do heavy lifting in Python.
* This adds a secondary ping-pong mechanism to make `keep_alive()` work. One that is slightly higher level, so that it stalls when JS is doing work (which is …
=> Better deletion prevention of Model objects

flexx/app/model.py, flexx/app/tests/test_model.py, flexx/ui/_widget.py
Fixes #228. Relates to closed issue #140 and PR #199.
So you can do:
```py
class MyModel(app.Model):
def init(foo, bar=3):
...
...
m = MyModel(7, 8, **properties_are_passed_as_kwargs_as_usual)
```
=> Model.init() can now have args

docs/scripts/genuiclasses.py, flexx/app/funcs.py, flexx/ui/widgets/__init__.py, flexx/ui/widgets/_tree.py
I am *very* happy with this :)
* TreeWidget can contain TreeItems, which are Model objects (not widgets).
* TreeItems can contain sub items.
* Construct using context manager and manipulate using `treewidget.items` and `treeitem.items`.
* Items are selectable (via a policy set at the tree widget).
* Items can be made checkable.
* Items can be collapsed/expanded if they are said to be so, or if they have sub items.
* Is implemented almost entirely in CSS; all that the JS does is apply CSS classes.
* This makes it very easy to style. Even changing the checkbox glyph etc.
In combination with the event system and the deep connector (`event.connect('tree.items**.xxx')`) this work very nice, I think.
=> TreeWidget

flexx/app/model.py, flexx/ui/_widget.py
This makes `Model` provide a method hook in JS that gets called when a handler is connected to an event that was previously unconnected. In `Widget` we use that hook to check if we need to support key events and set the `tab_index` if necessary. Over time, we might want to use this hook for other purposes as well (e.g. mouse events prevent-default stuff?)
=> Fix tabindex and still make key events Just Work

.gitignore, flexx/ui/widgets/_dropdown.py, flexx/ui/widgets/_tree.py
The expanded part of the dropdown is now `display: fixed`, so it is drawn over everything else.
=> Fix dropdown hidden overflow

flexx/ui/widgets/_dropdown.py
Continuation of #245
* `ComboBox`s `options` property is now a list of tuples `(key, text)`.
* It also has `selected_key` analog to `selected_index`, but holding the key corresponding to the selected item (or None).
=> ComboBox improvements: selected_key prop

flexx/pyscript/functions.py, flexx/ui/_widget.py
Essentially undoes #251 and adds docs on how to do it in a different way.
Also snuck in small fix to `py2js`.
=> Preventing default key press action by overloading key_press emitter

flexx/__main__.py, flexx/app/assetstore.py, flexx/app/clientcore.py, flexx/app/funcs.py, flexx/app/tornadoserver.py, flexx/pyscript/parser2.py, flexx/ui/examples/serve_data.py
Earlier on we made Flexx host its assets and data at `/_assets/...` and `/_data/...`, reserving the underscore for non-app Flexx stuff. This PR changes this so that all things that Flexx serves---except app pages---are prefixed by `/flexx/` (and `flexx` is an invalid app name). This way, when Flexx is run in another Tornado app (e.g. JLab, and possibly the notebook) we avoid name clashes.
This also splits the Tornado request handler in two parts: the `AppHandler` only serves apps and the app index page. The `MainHandler` handles serves everything else (using the `/flexx/` prefix). That way, we can only add the `MainHandler` when no app pages need to be served.
Along the same line, the `WSHandler` (websocket handler) now serves at `/flexx/ws/...`.
Further, there are a few changes related …
=> Making it possible to run Flexx via a 3d party Tornado app (aka JLab integration part 2)

flexx/_config.py, flexx/app/assetstore.py
Modules that were not served, but needed later were not loaded. This fixes that. Also add a config option to load *all* modules corresponding to imported Model classes (and their dependencies), so that larger apps that dynamically instantiate classes can still load everything beforehand.
=> Fix loading assets

docs/app/api.rst, flexx/app/__init__.py, flexx/app/funcs.py, flexx/app/model.py, flexx/app/session.py, flexx/ui/_widget.py, flexx/ui/examples/chatroom.py, flexx/ui/examples/demo.py
This PR continuous #236, awaiting the merge of ~~#225~~ #271 because it touches parts of the session manager that we need to change as well.
This add an `App` class, so that positional and keyword arguments can be provided for an app:
``` py
app.App(MyModel, 2, 3, text='bla').launch()
```
The `app.launch()` and friends (`serve`, `export`) continue to exist, but will take a `Model` class, wrap it in an `App`, and call its corresponding method.
It will (probably) also allow stuff like this, useful for e.g. testing:
``` py
my_app = app.App(MyModel, 2, 3, text='bla')
my_app.serve()
my_app.name
my_app.url  # though this would need the server to be running
```
=> app.App class

flexx/app/asset.py, flexx/app/assetstore.py, flexx/app/clientcore.py, flexx/app/session.py
This shows a simple "spinner" during startup. It gets displayed very quickly during page load, so that when startup takes a bit longer, you know that it at least is doing something. It shows a kind of progress bar that consists of small squares, one for each module being loaded.
Startup time consists of two parts: loading the assets, instantiating the models. The Flexx server sends a special command right after emptying its queue of pending commands into the websocket, which tells the client that initialization is done and that the spinner can be hidden.
=> Show spinner during startup

flexx/app/funcs.py, flexx/app/tornadoserver.py
Fix for a problem introduced in #277 (or slightly before that?). The server did redirect urls to apps if needed, but that code was lost in a refactoring. This brings it back.
=> Ensure app url ends with slash

flexx/event/_handler.py, flexx/event/tests/test_handlers.py, flexx/util/testing.py, make/test.py
And fix how we call `pytest.main()`.
=> Raise error when trying to use "*" in connection string inproperly.

flexx/app/asset.py, flexx/app/modules.py, flexx/app/tests/test_asset.py
Modules might need core Flexx stuff. But more importantly, the asset uses `flexx.spin`.
=> All modules implicitly depend on flexx.app.clientcore

flexx/pyscript/parser0.py, flexx/pyscript/parser1.py, flexx/pyscript/parser2.py, flexx/pyscript/stdlib.py, flexx/pyscript/tests/test_parser1.py
* mangle the names of the funcs that implement method overloading
* make sure these are ignored as builtins (so you can even define a function `op_add`, and it should still work.
=> Pyscript: avoid name clashes with our operator overload funcs

docs/pyscript/api.rst, flexx/app/clientcore.py, flexx/app/modules.py, flexx/app/tests/test_module.py, flexx/pyscript/__init__.py, flexx/pyscript/functions.py, flexx/pyscript/parser2.py, flexx/pyscript/parser3.py, flexx/pyscript/stubs.py, flexx/pyscript/tests/test_parser1.py, flexx/pyscript/tests/test_parser2.py, flexx/pyscript/tests/test_parser3.py, flexx/pyscript/tests/test_stubs.py, flexx/ui/examples/with_jquery.py, flexx/util/minify.py
Fixes #279, possibly makes #275 easier, helps #104 while honoring #259.
Write raw JS:
```py
RawJS('$')(self.node).datepicker()
...
def foo(x):
res = []
RawJS("""
for (i=0; i<10; i++) {
...
}
""")
```
Define globals in app, ui:
```py
some_module = RawJS("require('some.module')")
foo = RawJS("[]")
from m1 import foo  # hooray, we can share a constant in JS!
```
=> Add RawJS construct for embedding raw JS and define global instances

flexx/app/assetstore.py, flexx/app/modules.py, flexx/ui/_widget.py, flexx/ui/layouts/_box.py, flexx/ui/layouts/_dock.py, flexx/ui/layouts/_grid.py, flexx/ui/layouts/_pinboard.py, flexx/ui/layouts/_split.py, flexx/ui/layouts/_stack.py, flexx/ui/layouts/_tabs.py, flexx/ui/widgets/_group.py, flexx/ui/widgets/_lineedit.py, flexx/util/getresource.py
* Make use of lastest Phosphor-all, which has a new API that uses a `window.require_phosphor()` function.
* Flexx' module loader `window.flexx.define` + `window.flexx.require` detects when something `phosphor/...` is required, and calls `window.jupyter.require()` or `window.require_phosphor()`.
* All widget modules load needed phosphor modules using `window.flexx.require()` (made possible by `RawJS` #290).
=> Allow running Phosphor provided by Jupyter

docs/app/api.rst, flexx/app/__init__.py, flexx/app/_model.py, flexx/app/_session.py, flexx/app/tests/test_model.py
This fixes a nasty bug that was introduced when the model id's were handed out per-session. This relates slightly to #272, we'd need to perform a similar trick on the client side in that case.
=> Models are register per session instead of globally

flexx/event/_handler.py
pscripted code read:
```
else if (_pyfunc_op_equals(selector, "*")) {
t = "Invalid connection \"%s\" because %s is not a tuple/list.";
err_3 = new Error('RuntimeError:' + (t % [obname_full, obname])); err_3.name = "RuntimeError"; throw err_3;
```
Which raised a NaN error on Chrome when trying to print this:
_"Invalid connection volumes* because volumes is not a tuple/list."_
It was instead doing this (in the js console):
```
t = "Invalid connection \"%s\" because %s is not a tuple/list."; # "Invalid connection "%s" because %s is not a tuple/list."
t % [obname_full, obname]  # returns NaN
```
This should fix this error.
=> Fixed string replace in events.

flexx/_config.py, flexx/app/_app.py, flexx/app/_clientcore.py, flexx/app/_funcs.py, flexx/app/_server.py, flexx/app/_tornadoserver.py, flexx/app/examples/serve_ssl.py
Proof of concept for #303
* Allows to pass arguments to `tornado.HTTPServer` constructor through `app.create_server`.
* support for HTTPS protocol
Enable SSL transport by calling :
```
args = {}
args['ssl_options'] = {'certfile' : 'path-to-crtfile', 'keyfile' : 'path-to-keyfile'}
app.create_server(**args)
app.serve(Example, 'Example')
app.run()
```
=> add support for HTTPS protocol

flexx/_config.py, flexx/app/_funcs.py, flexx/app/_tornadoserver.py
* app.init_notebook() fix added WSS to url
* TornadoServer  Comparing hostnames in case of Jupyter notebooks connecting_host and serving_host have same host names but different ports
=> SSL support for remotely running Jupyter notebooks

flexx/ui/examples/code_editor.py
This could later be extended (e.g. get properties to toggle line numbers, syntax highlighting, etc.) and put as a widget in the library.
=> Add example for code editor widget based on codemirror

flexx/ui/widgets/_color.py, flexx/ui/widgets/_lineedit.py, flexx/ui/widgets/_slider.py
Copying #314 code to LineEdit widget.
This could probably apply to all widgets based on a `<input>` tag.
Can we just do the same for BaseDropDown widget?
=> add disabled property to LineEdit

flexx/pyscript/parser3.py, flexx/ui/examples/code_editor.py, flexx/ui/examples/code_editor_ace.py, flexx/ui/examples/code_editor_cm.py
This PR fixes the Python syntax not being highlighted.
It also makes the example a little more impressive by showing how easy it is to change themes and enable features.
=> make CodeMirror example more impressive

flexx/app/_model.py, flexx/event/__init__.py, flexx/event/_handler.py, flexx/event/_hasevents.py, flexx/event/_js.py, flexx/event/tests/test_both.py, flexx/event/tests/test_handlers.py, flexx/pyscript/examples/js_module.js, flexx/pyscript/functions.py, flexx/pyscript/parser0.py, flexx/pyscript/parser2.py, flexx/pyscript/tests/test_parser1.py, flexx/pyscript/tests/test_parser2.py, flexx/ui/examples/classic_web_dev.py, flexx/ui/layouts/_box.py, flexx/ui/layouts/_form.py, flexx/ui/layouts/_grid.py, flexx/ui/layouts/_pinboard.py, flexx/ui/widgets/_tree.py
* Fixes #194: formalize the syntax for connection strings.
* Make sure normalization/checks are done in the right places.
* Fixes connection string that end in deep connector.
* Fixes a few other corner cases that where bugs but simply never showed up yet.
* The code grew somewhat, so I had to finally make `evaljs` pass the code to `node` via a file.
* Which gave some space, so I got rid of the `Ƥ` placeholder for `prototype`.
* Make functions not anonymous (which makes handlers for which no label is specified sill still have a sensible label).
=> Settle on a syntax for connection strings

flexx/event/_hasevents.py, flexx/event/_js.py, flexx/event/tests/test_both.py, flexx/pyscript/functions.py, flexx/pyscript/parser2.py, flexx/pyscript/stdlib.py, flexx/pyscript/tests/test_parser2.py
* Fixes a nasty bug that broke things for closures that were called recursively inside a method, and `self` was used inside it.
* Methods remain anonymous (but we set `__name__` on them). Other functions (that are not lambdas) are named functions, but prefixed with "flx_"  to prevent calling the unbound method from a bound function.
* Fixes #212 consistent order of setting properties.
=> Fix recursion bug for named functions

docs/start.rst, docs/webruntime/index.rst, flexx/ui/_widget.py, flexx/ui/examples/boxpanel_vs_boxlayout.py, flexx/ui/layouts/__init__.py, flexx/ui/layouts/_box.py
* Add HBoxPanel and VBoxPanel to be consistent with HBox and VBox
* Clarify docs about the differences between BoxPanel and BoxLayout
* Add an example to demonstrate these differences
* Fixed that BoxPanel actuall uses `Widget.base_size` (it was hard-coded to 100).
The example app: https://dl.dropboxusercontent.com/u/1463853/differentboxes.html
=> BoxPanel clarifications

flexx/ui/layouts/_box.py
I guess this bug surfaced because the base width was reduced lately.
=> Fix flexbox odities (e.g. splines app on Chrome)

flexx/webruntime/__init__.py, flexx/webruntime/common.py, flexx/webruntime/nodewebkit.py, flexx/webruntime/tests/test_dont_leave_trails.py, flexx/webruntime/xul.py
We already had this covered for NW.js, now we apply the same strategy for xul.
=> Make XUL use an explicit profile dir

flexx/ui/examples/leaflet.py
Added leaflet widget as an example.
The example 
- shows a map in a xul window
- shows how to add and remove layers
- contains checkboxes for showing the layer control and scale
- reponds to mouse clicks by adding markers to the map
I intended to make the widget reflect more of leaflet's API, but found it quite hard to come up with a generic way to do so, in particular because different applications would probably want a different level of Py <-> JS communication. I was thinking of creating a dictionary in JS with GUID->JavascriptObject entries and using the GUIDs as a reference to these objects in python, but I don't know if that's the way to go. Maybe you have some ideas on that. I am going to leave the example as it is for now.
=> Add leaflet example

flexx/_config.py, flexx/app/_app.py, flexx/app/_clientcore.py, flexx/app/_funcs.py, flexx/app/tests/test_live.py, flexx/ui/examples/leaflet.py, flexx/ui/widgets/_lineedit.py, flexx/webruntime/__init__.py, flexx/webruntime/_browser.py, flexx/webruntime/_chrome.py, flexx/webruntime/_common.py, flexx/webruntime/_firefox.py, flexx/webruntime/_manage.py, flexx/webruntime/_ms.py, flexx/webruntime/_nw.py, flexx/webruntime/_qt.py, flexx/webruntime/_selenium.py, flexx/webruntime/tests/test_dont_leave_trails.py
This PR adds lets the `webruntime .launch()` function make use of the dialite package to show a dialog when the runtime is not available or fails, or when none of the possible runtimes is available. This provides a friendly way to present the user with instructions for installing a runtime, which is particularly important for frozen applications (when the end-user can be non-programmers).
=> Show useful dialogs at runtime fail

.travis.yml, LICENSE, docs/conf.py, docs/scripts/genexamples.py, flexx/app/_model.py, flexx/event/_js.py, flexx/pyscript/commonast.py, flexx/ui/examples/send_data.py, flexx/util/icon.py, setup.py
Notes:
* Python 3.6 introduced `ast.Constant` but `ast.parse()` does not seem to produce it; its intended for 3d party libs.
* Python 3.6 allows underscores as string literals, the produced ast produced regular literals, so no action required.
=> Support Python 3.6

flexx/pyscript/__init__.py
Changed `pry` to `try` in `flexx/pyscript/__init__.py` file.
This typo showed itself in the [auto-generated documentation](http://flexx.readthedocs.io/en/latest/pyscript/intro.html#quick-intro)
=> Corrected typo in flexx.pyscript documentation

flexx/ui/_widget.py
Was fixed for BoxPanel, but not for several other layout classes that use absolute positioning.
=> Fix embedding SplitPanel (and others) in VBox with Widget in between

flexx/pyscript/parser0.py, flexx/pyscript/parser1.py, flexx/pyscript/parser2.py, flexx/pyscript/tests/test_parser2.py
Closes #288
Before this PR, list comprehensions are transpiled to an inline function that is immediately called, and which always is a closure. This PR makes PyScript produce a for-loop where possible, and in other cases reduces the chance of the in-line function to become a closure.
Also see https://developers.google.com/speed/articles/optimizing-javascript
=> Pyscript: transpile listcomps to for-loops where possible

flexx/app/_clientcore.py, flexx/app/_model.py, flexx/event/_handler.py, flexx/ui/_widget.py, flexx/ui/layouts/_tabs.py, flexx/ui/widgets/_button.py, flexx/ui/widgets/_canvas.py, flexx/ui/widgets/_color.py, flexx/ui/widgets/_dropdown.py, flexx/ui/widgets/_lineedit.py, flexx/ui/widgets/_media.py, flexx/ui/widgets/_slider.py, flexx/ui/widgets/_tree.py
In applications that dynamically create and destroy ui elements, the widgets were apparently not cleaned up correctly. There were dangling references to the objects in different places. This PR improves this.
As a reminder, this is more or less how memory management works in the current Flexx: Python is used as the "reference" object. We let the Python gc do its thing, and when it cleans something up, we call `dispose()` via `__del__`. This does some cleanup and calls `dispose()` at the JS side. One can call `dispose()` at the Py side explicitly as well. But probably better not do it at the JS side.
Measures that this PR takes:
* Add `Model._addEventListener()` that removes the event listeners in `dispose()`.
* Remove Phosphor listeners in `dispose()`.
* Dispose of objects via …
=> Less memory leaks

flexx/app/_session.py, flexx/ui/widgets/_lineedit.py
Adds a convenience method on `Session` to overcome jitter effects. We keep patching things up, but really, this idea of objects that exist in both Python and JS is flawed.
=> add Session.call_after_roundtrip

.travis.yml, flexx/pyscript/tests/test_parser1.py, flexx/ui/widgets/_dropdown.py, flexx/ui/widgets/_tree.py, flexx/util/tests/test_import.py
* `TreeItem.mouse_click` and `TreeItem.mouse_double_click` events now carry more information about buttons and modifier keys (needed to implement the below).
* When `max_selected` is `<1`, one can use `Ctrl` and `Shift` to select multiple items.
* To get the old behavior, use `max_selected=1e9`.
* Doubleclicking an item selects it (previously it would just toggle on and off (or off and on).
Also fixed issues with Travis CI / Pytest / Pypy.
=> TreeWidget multiselect with Ctrl and Shift

flexx/ui/examples/control_with_keys.py, flexx/ui/widgets/_tree.py
* Highlight tracks item clicks
* Highlighted item scrolls into view when needed
* Show how scrolling when pressing arrow keys can be turned off (though in another use-case this appraoch somehow fails)
=> Tree key control improvements

flexx/ui/widgets/_tree.py
This fixes a problem where double clicking events weren't emitted
=> Added missing return statement

flexx/_config.py, flexx/app/_tornadoserver.py
Here's a pull request for  issue #393 that I just created.   
I added a config attribute to set tornado debug mode.   
I tried some test scripts for this, but it was a little tricky reloading the app without reloading the test.
=> add config tornado_debug to allow running tornado in debug mode

flexx/_config.py, flexx/app/_tornadoserver.py
On a production server it's not desirable to show users a stack trace in case of an error. Depending on the audience this might be for user friendliness or security reasons. I feel the option should default to False, but set to True for now to maintain current behaviour.
=> Added config option to disable stack trace in browser window

flexx/app/_clientcore.py
otherwise doing the beforeunload dialog trick will still break the app.
=> Close websocket on unload instead of beforeunload

flexx/app/_asset.py, flexx/app/_clientcore.py, flexx/ui/_widget.py, flexx/ui/examples/boxes.py, flexx/ui/examples/chatroom.py, flexx/ui/examples/hv_layout.py, flexx/ui/examples/monitor.py, flexx/ui/examples/send_data.py, flexx/ui/examples/serve_data.py, flexx/ui/examples/store.py, flexx/ui/examples/twente.py, flexx/ui/examples/using_python_in_js.py, flexx/ui/layouts/_tabs.py, flexx/ui/widgets/_bokeh.py, flexx/ui/widgets/_button.py, flexx/ui/widgets/_dropdown.py, flexx/ui/widgets/_group.py, flexx/ui/widgets/_label.py, flexx/ui/widgets/_media.py, flexx/webruntime/_common.py
Closes #293 
This makes it harder to insert raw html in your app. There are still two places where this is possible: the `Label.html` property, where we put a warning in the docs, and via `_render_dom` by providing an `innerHTML` prop, in which case the user probably knows what she is doing, and we warn for it in the docs.
We make use of  `textContent` instead of  `innerHTML` in several places. The `Label` class now has a text and html property, setting either updates both (let the browser do the work, because one can set `textContent` and get `innerHTML` and vice versa).
Also snuck in a tweak to increase the chance of closing the webruntime when Python is killed.
=> Changes to not open things up for xss attacks

flexx/ui/layouts/_hv.py, flexx/ui/layouts/_tabs.py, flexx/ui/widgets/_button.py, flexx/ui/widgets/_color.py, flexx/ui/widgets/_dropdown.py, flexx/ui/widgets/_lineedit.py, flexx/ui/widgets/_slider.py, flexx/ui/widgets/_tree.py, flexxamples/testers/tricky_events.py
It's not uncommon for an input widget to be used to update a certain value of an item, but also to set the widget once another item becomes "active". This can cause annoying behavior which can usually be dealt with, but not without jumping through a hoop or two.
This PR adds emitters that can be reacted to, that emit specifically for user interaction (i.e. not programmatic updates). I think I've got all input widget, and even two layout widgets.
=> New emitters for input widgets to better distinguish user input

MANIFEST.in, flexx/app/_clientcore.py, flexx/ui/_widget.py, flexx/ui/layouts/_form.py, flexx/ui/layouts/_hv.py, flexx/ui/layouts/_tabs.py, flexx/ui/widgets/_bokeh.py, flexx/ui/widgets/_button.py, flexx/ui/widgets/_canvas.py, flexx/ui/widgets/_color.py, flexx/ui/widgets/_dropdown.py, flexx/ui/widgets/_group.py, flexx/ui/widgets/_iframe.py, flexx/ui/widgets/_label.py, flexx/ui/widgets/_lineedit.py, flexx/ui/widgets/_media.py, flexx/ui/widgets/_plotwidget.py, flexx/ui/widgets/_progressbar.py, flexx/ui/widgets/_slider.py, flexx/ui/widgets/_tree.py, flexxamples/demos/chatroom.py, flexxamples/demos/colab_painting.py, flexxamples/demos/splines.py, flexxamples/demos/twente.py, flexxamples/howtos/bokehdemo.py, flexxamples/testers/minsize.py
Closes #209
* tree items allow more space for text if there is no title
* Widget gets minsize and maxsize properties. These are the reference for minimum and maximum size, not the CSS!
* Though using `apply_style()` still works, because we can easily capture the setting of min-width and friends.
* The layouts are now much better able to communicate size limits upstream. This works around the flexbox bug that size limits is not properly taken into account for certain child configurations, plus we can communicate the limits over singleton widgets (common for custom classes that have a single layout child).
* Every widget that has some content has a proper default minimum size (set via a class property).
* E.g. group widgets now also work much better in different layouts.
* Fixes to …
=> Tweaks to layout and CSS

flexx/ui/_widget.py
It seems that the gist of it to always use keydown, unless I miss something.
=> Improve docs on Widget.keypres event

flexx/ui/_widget.py
Previously, an example like this would give the created label the `box` as its parent, which seems odd, because we explicitly pass `None`. This PR fixes that. The context is needed to tell Flexx what session the widget belongs to.
```py
from flexx import flx
class Example(flx.Widget):
def init(self):
self.box = flx.HBox()
@flx.action
def foo(self):
with self.box:
self.label = flx.Label(text='hi', parent=None)
```
=> Widgets van be orphaned upon initialization by setting parent to None

flexx/ui/_widget.py, flexx/ui/layouts/_hv.py
Use-case one: in a splitter widget, sometimes you just want to be able to collapse the content all the way.
Use-case two: if a widget inside a splitter widget has a lot of content, you sometimes don't want it to take the full space (and more) of the splitter. 
This adds a `minsize_from_children` property to the `Widget` class that can be set to False, so that only the intrinsic `minsize` of the widget is used to calculate its size constraints.
=>  Add Widget.minsize_from_children property 

flexx/app/bsdf_lite.py, setup.cfg
(this just copies over the latest bsdf_lite.py from the bsdf project)
=> update bsdf Python implementation: implicit conversion of numpy scalars

flexx/ui/widgets/_tree.py
This is a tweak to the TreeItem to better distinguish between the whole item (including children) and only the row. We already had `Widget.outernode` and `Widget.node` for this, but we had not used them in this case yet. This is in preparation for implementing item dragging (here, or as a subclass where its needed).
=> Give TreeItem an outernode

flexx/app/_app.py, flexx/app/_asset.py, flexx/app/_component2.py, flexx/app/_funcs.py, flexx/app/_modules.py, flexx/app/_session.py, flexx/app/_tornadoserver.py, flexx/app/bsdf_lite.py, flexx/event/_action.py, flexx/event/_component.py, flexx/event/_js.py, flexx/event/_loop.py, flexx/event/_reaction.py, flexx/event/tests/test_actions.py, flexx/util/config.py, flexx/util/tests/test_logging.py
* Stop using deprecated `inspect.getargspec()`
* Stop using deprecated `logger.warn()`
=> Fix tests and get rid of some warnings

flexx/app/_funcs.py, flexx/app/_server.py
Can be interrupted without hanging. Interruptions will no longer cause weird tracebacks. Closes #529
=> Better shutdown behavior

flexx/app/_tornadoserver.py, flexx/app/tests/test_funcs.py
Here's a start. I guess checking for a url could be done, but that would have to be part of the "spec" then I guess.
=> Adds test (and comment) on 'Serving apps at' ready signal

docs/about.rst, docs/freeze.rst, flexx/app/_funcs.py, flexx/ui/_widget.py, flexx/ui/layouts/__init__.py, flexx/ui/layouts/_form.py, flexx/ui/layouts/_grid.py, flexx/ui/widgets/__init__.py, flexx/ui/widgets/_bokeh.py, flexx/ui/widgets/_lineedit.py, flexx/util/freeze.py
* Implements `FormLayout` using css grid. Closes #422.
* Implements new `GridLayout` using css grid.
* Implements new `MultiLineEdit`.
* Support code for freezing.
* Docs. Closes #552
* TODO: see if freezing can be implemented as simple as `App.freeze()`.
=> Several enhancements

flexx/app/_funcs.py
Maybe you would have preferred an issue report, but since I had to fix it, I thought I'd share the fix instead. The IPython imports fail for me. 
I have to admit I'm not entirely sure I understand the reason for the #noqa style import. Also I don't understand how this has ever worked, so forgive me if I'm just being an idiot here...  
Doing a 'regular' import certainly fixes the issue, but since there must be some reason why you did it this way, I decided to fix it without removing  the `exec`.
See e.g. https://bugs.python.org/issue4831
=> Fix ipython import for notebooks

flexx/ui/widgets/_group.py
* GroupWidget determined dimensions should take precedence. #593
=> Mark GroupWidget determined dimensions !important

flexx/ui/_widget.py
Because of the CSS parsing, apply_style() would split on any colon which would split http:// links. With this small change it will only split on the first colon and then on the next semicolon for a next line of css
=> Allow colon passed to apply_style()

docs/guide/widgets_components.rst
Changed "dicsussed" to "discussed" in docs/guide/widgets_components.rst
=> Fix a typo in docs/guide/widgets_components.rst

docs/guide/reactions.rst, docs/guide/widgets_components.rst
Changed "consisten" to "consistent" and "simultenously" to "simultaneously"  in docs/guide/reactions.rst
=> Fix typos in docs/guide/reactions.rst

flexx/app/_assetstore.py
I add an issue when using `flx.assets.associate_asset(__name__, 'https://cdn.plot.ly/plotly-latest.min.js')` in my __main__ module. Turns out the asset store was not detecting the name in it's list of loaded assests as the name in the dict is shorten to the filename.
I applied correction an now submitting. 
Thanks,
=> Issue when validating the existance of an asset when the asset is a link

flexx/app/_app.py
encodestring is deprecated since 3.1,
was still available until 3.8,
gone in 3.9
encodebytes since 3.1, too
=> fix deprecated lib call

flexx/app/_component2.py, flexx/app/_flaskserver.py, flexx/event/_component.py, flexx/ui/_widget.py, flexxamples/howtos/bokehdemo.py
Hi almarklein, I would like to push a change to have more symmetry between PyWidget and Widget:
I can do:
```
with ui.Widget(style=overlay_style+"width:0%;") as self.waiting_overlay:
(...)
```
But could not do:
```
with ui.PyWidget(style=overlay_style+"width:0%;") as self.waiting_overlay:
(...)
```
Which I found anoying as I'm using server side processing quite a lot and need to switch Widget from one side to the other seamlessly. 
I changed the `bokehdemo.py` and inserted a PyWidget within to show the style in action.
I have a lot of other things relying on this change so I hope it goes forward one way or another. I hope to submit them at a later point when they get more reliable.
P.S. there is also an optimisation for flask serving within the code (in _flaskserver.py).
Thank you for …
=> Symmetry betwee PyWidget and Widget

docs/guide/widget_basics.rst, flexx/app/_session.py, flexx/app/tests/test_asset.py, flexx/event/_js.py, flexx/event/_reaction.py, flexx/ui/_widget.py, flexx/util/tests/test_config.py, flexxamples/howtos/echarts_example.py, flexxamples/testers/tricky_events.py
There are small typos in:
- docs/guide/widget_basics.rst
- flexx/app/_session.py
- flexx/app/tests/test_asset.py
- flexx/event/_js.py
- flexx/event/_reaction.py
- flexx/ui/_widget.py
- flexx/util/tests/test_config.py
- flexxamples/howtos/echarts_example.py
- flexxamples/testers/tricky_events.py
Fixes:
- Should read `precedence` rather than `precedense`.
- Should read `assets` rather than `assests`.
- Should read `simultaneously` rather than `simultenously`.
- Should read `service` rather than `survice`.
- Should read `occurrence` rather than `occurance`.
- Should read `eliminate` rather than `elliminate`.
- Should read `declarative` rather than `declerative`.
- Should read `children` rather than `childen`.
- Should read `capturing` rather than `caputuring`.
- Should read `aggregated` …
=> docs: Fix a few typos
