- flexx/webruntime/qtwebkit.py
> PyQt5 fix proposal

- examples/ui/bokeh_plot.py
Awesome demo Almar, just fixing the label text :)
> Fix minor typo.

- examples/ui/cpu_monitor.py
- examples/ui/twente_temperature.py
- examples/ui/with_bokeh.py
- flexx/app/funcs.py
- flexx/app/model.py
- flexx/app/session.py
- flexx/app/tornadoserver.py
- flexx/ui/_canvaswidget.py
- flexx/ui/_widget.py
- flexx/ui/widgets/_bokeh.py
- flexx/ui/widgets/_button.py
- flexx/ui/widgets/_lineedit.py
- flexx/ui/widgets/_plotwidget.py
Fixes some issues and loose ends from the previous PR. Plus some improvements here and there.
> Several improvements

- examples/app/benchmark.py
- examples/notebooks.txt
- examples/ui/circles.py
- examples/ui/cpu_monitor.py
- examples/ui/hello_world.py
- examples/ui/with_bokeh.py
- flexx/app/assetstore.py
- flexx/app/session.py
- flexx/app/tornadoserver.py
- flexx/pyscript/parser0.py
- flexx/pyscript/stdlib.py
- flexx/pyscript/tests/test_stdlib.py
- flexx/ui/layouts/_pinboard.py
- setup.py
> Various small fixes and improvements

- docs/cli.rst
- docs/index.rst
- flexx/__main__.py
- flexx/app/tornadoserver.py
- flexx/util/tests/test_cli.py
Closes #69. This PR does not cover all use-cases presented in that PR, but its a good start, and other use-cases can follow in new PR's over time.
> Implementation of CLI, with func to stop a server.

- flexx/util/testing.py
- flexx/util/tests/test_import.py
> Skip some tests for Pypy on Travis

- flexx/app/tests/test_live.py
> enable live test on travis

- docs/releasenotes.rst
- docs/tutorials/layout.rst
- flexx/react/__init__.py
- flexx/ui/layouts/_box.py
- flexx/util/icon.py
A few small things, see commits. Closes #84
> BoxLayout margin -> padding, docs, warn for react deprecation

- flexx/pyscript/__init__.py
- flexx/pyscript/parser2.py
- flexx/pyscript/tests/test_parser2.py
- flexx/react/pyscript.py
- flexx/ui/_widget.py
- flexx/ui/widgets/_bokeh.py
- flexx/ui/widgets/_button.py
- flexx/ui/widgets/_canvas.py
- flexx/ui/widgets/_lineedit.py
- flexx/ui/widgets/_slider.py
> Implement bound methods

- docs/releasenotes.rst
- flexx/app/funcs.py
- flexx/app/session.py
- flexx/pyscript/__init__.py
- flexx/pyscript/parser0.py
- flexx/react/signals.py
- flexx/webruntime/common.py
- make/clean.py
> Various small tweaks

- flexx/ui/widgets/__init__.py
- flexx/ui/widgets/_button.py
- flexx/ui/widgets/_color.py
- flexx/ui/widgets/_lineedit.py
- flexx/ui/widgets/_media.py
> Implement extra widgets

- flexx/webruntime/xul.py
> Fix locating firefox on OS X (part 2)

- flexx/webruntime/__init__.py
- flexx/webruntime/browser.py
- flexx/webruntime/common.py
- flexx/webruntime/xul.py
* Fixes #150
* Adds Flexx logging to webruntime module
> Fixes for XUL runtime

- docs/app/api.rst
- flexx/app/__init__.py
- flexx/app/examples/adding_handlers.py
- flexx/app/examples/flexx_in_thread.py
- flexx/app/funcs.py
- flexx/app/tests/test_funcs.py
- flexx/app/tests/test_live.py
- flexx/app/tests/test_model.py
- flexx/app/tornadoserver.py
- flexx/event/_loop.py
Fixes #152 
cc @korijn @Maxyme
> Refactor tornado server

- flexx/ui/_widget.py
And add example that had the problem (but works fine now).
> Fix nesting of vbox/hbox/widget on Chrome

- .travis.yml
- flexx/webruntime/qtwebkit.py
- make/test.py
- setup.cfg
> Improve and fix pyqt webruntime

- flexx/app/clientcore.py
- flexx/app/session.py
- flexx/app/tests/test_model.py
- flexx/app/tornadoserver.py
- flexx/event/_handler.py
- flexx/ui/examples/errors.py
- flexx/util/logging.py
- flexx/util/tests/test_logging.py
Solves #164. Not sure if this is the best way to solve it thoug.
> Prevent websocket close

- flexx/app/assetstore.py
- flexx/ui/examples/with_jquery.py
And also some small changes to assetstore (because that is where I started looking for the error).
> Fix jquery example

- flexx/app/funcs.py
- flexx/app/model.py
- flexx/app/tests/test_funcs.py
- flexx/app/tests/test_live.py
- flexx/app/tests/test_model.py
- flexx/event/_handler.py
- flexx/event/_hasevents.py
- flexx/event/_js.py
- flexx/event/_loop.py
- flexx/event/tests/test_both.py
- flexx/event/tests/test_emitters.py
- flexx/event/tests/test_handlers.py
- flexx/event/tests/test_hasevents.py
- flexx/event/tests/test_loop.py
- flexx/pyscript/functions.py
Related to #146
Also fixes Bokeh example.
> Improve initial event caching.

- flexx/pyscript/parser2.py
- flexx/pyscript/tests/test_parser2.py
- flexx/ui/_widget.py
- flexx/ui/layouts/_box.py
- flexx/ui/layouts/_split.py
- flexx/ui/layouts/_stack.py
- flexx/ui/widgets/_bokeh.py
- flexx/ui/widgets/_color.py
Fixes #185 
Also made pyscript able to re-raise an exception object (`Error` object in JS).
> Better error reporting by also mentioning model id

- docs/scripts/uiexample.py
- flexx/app/session.py
> Fix doc building

- flexx/ui/__init__.py
- flexx/ui/_widget.py
- flexx/ui/examples/classic_web_dev.py
- flexx/ui/widgets/__init__.py
- flexx/ui/widgets/_button.py
- flexx/ui/widgets/_html.py
> Functionality to create widgets representing plain HTML elements

- flexx/ui/widgets/__init__.py
- flexx/ui/widgets/_dropdown.py
* A `ComboBox` is an optionally editable dropdown button
* A `DropdownContainer` can hide a widget out of sight.
> Add combobox/dropdown

- flexx/ui/widgets/_dropdown.py
- flexx/ui/widgets/_tree.py
> Use more common glyphs for tree and combobox "expand"

- flexx/ui/widgets/_tree.py
> TreeWidget first unselects then selects.

- flexx/app/funcs.py
- flexx/app/session.py
> Handle main url in single place

- flexx/webruntime/chromeapp.py
> Fixes #286

- docs/scripts/genexamples.py
- docs/scripts/uiexample.py
Relates to #210
This helps with testing---or maybe a better word is *checking*---that all ui examples seem to work.
> Add overview page to docs with ALL ui examples

- flexx/app/model.py
- flexx/app/session.py
- flexx/event/_hasevents.py
See commits for an overview.
Fixes #269
> Tweaks to flexx.app

- flexx/ui/widgets/_button.py
Added a property to set buttons to disabled and reverse.
> added disabled property to button

- flexx/app/__init__.py
- flexx/app/_app.py
- flexx/app/_asset.py
- flexx/app/_assetstore.py
- flexx/app/_clientcore.py
- flexx/app/_funcs.py
- flexx/app/_model.py
- flexx/app/_modules.py
- flexx/app/_session.py
- flexx/app/_tornadoserver.py
- flexx/pyscript/parser1.py
- flexx/pyscript/stdlib.py
* Fixes #270 - tracebacks for errors in serializer are shorter (and serializer actually fails on JS when it must)
* Closed #276 - last remaining bit were a few todo's related to the use of `App`.
> Various small improvements fixes and cleanup in flexx.app

- flexx/ui/_widget.py
> Doc to use key_down to prevent browser default action

- flexx/app/_tornadoserver.py
- flexx/app/examples/benchmark.py
> fixes for python 2

- flexx/webruntime/qtwebkit.py
The QtWebkit runtimes don't appear to work on my machine, but PySide2 should be similar to PyQt5. At least now it'll try to do something. A basis for further fixing.
> Enable PySide2 QtWebKit runtime

- flexx/webruntime/__init__.py
- flexx/webruntime/_manage.py
- flexx/webruntime/browser.py
- flexx/webruntime/chromeapp.py
- flexx/webruntime/common.py
- flexx/webruntime/nodewebkit.py
- flexx/webruntime/qtwebkit.py
- flexx/webruntime/selenium.py
- flexx/webruntime/tests/test_functions.py
- flexx/webruntime/xul.py
> Adding proper NW runtime plus improvements to others

- docs/webruntime/index.rst
- flexx/_config.py
- flexx/ui/examples/splines.py
- flexx/webruntime/__init__.py
- flexx/webruntime/_manage.py
- flexx/webruntime/browser.py
- flexx/webruntime/chromeapp.py
- flexx/webruntime/common.py
- flexx/webruntime/mshtml.py
- flexx/webruntime/nodewebkit.py
- flexx/webruntime/qtwebkit.py
- flexx/webruntime/selenium.py
- flexx/webruntime/tests/test_runtimes.py
- flexx/webruntime/xul.py
#338 needs to be merged first.
> Refactoring of runtime classes

- flexx/ui/_widget.py
- flexx/ui/layouts/_box.py
Also allow setting `base_size` with one integer to set width and height at the same time.
> Add example in BoxPanel/BoxLayout docs

- flexx/dialite/__init__.py
- flexx/dialite/tests/test_dialite.py
- flexx/webruntime/tests/test_runtimes.py
Also adds `NoDialogs()` context manager for use in tests.
> Dialite create app lazily, so no os calls unless actually used.

- flexx/ui/layouts/_split.py
> Make splitpanel aware of flex and add spacing prop

- flexx/app/_app.py
- flexx/app/_tornadoserver.py
> Prevent Flexx from instantiating app when browser requests favicon.ico

- flexx/ui/widgets/_tree.py
> Fixes to TreeWidget

- docs/scripts/genexamples.py
- flexx/app/_app.py
Also seem to have fixed the iffy CI for the doc build test
> Avoid double slash in url for root apps

- flexx/app/_app.py
- flexx/app/_session.py
- flexx/app/_tornadoserver.py
It follows the same logic as setting the cookies: it is added to
the object right after it has been constructed and makes sense
only in the scope of web applications.
> Insert the path into the session when creating it

- docs/scripts/genexamples.py
- flexx/app/_model.py
- flexx/event/_hasevents.py
- flexx/event/tests/test_hasevents.py
This hopefully fixes:
```
Exception ignored in: <bound method HasEvents.__del__ of <Visual object 'Visual70' at 0x22a3393d780>>
Traceback (most recent call last):
File "C:\Users\john\Miniconda3\envs\xx\lib\site-packages\flexx\event\_hasevents.py", line 188, in __del__
self.dispose()
File "C:\Users\john\Projects\xx\xx\viz\visuals\visual.py", line 65, in dispose
self.children = ()
File "C:\Users\john\Miniconda3\envs\xx\lib\site-packages\flexx\app\_model.py", line 500, in __setattr__
event.HasEvents.__setattr__(self, name, value)
File "C:\Users\john\Miniconda3\envs\xx\lib\site-packages\flexx\event\_emitters.py", line 121, in __set__
return instance._set_prop(self._name, value)
File "C:\Users\john\Miniconda3\envs\xx\lib\site-packages\flexx\app\_model.py", line 538, in _set_prop …
```
> Call dispose later from __del__ so it gets called in Tornados handlers

- flexx/event/_handler.py
- flexx/event/tests/test_handlers.py
In one particular use-case, this significantly improves performance.
@ivoflipse @korijn
> Improve performance of event reconnecting

- .gitignore
- flexx/app/_app.py
- flexx/ui/examples/splines.py
With "the cloud" being a cheap AWS Lightsail instance. But it's a start!
> Apps can now be published in the cloud

- docs/start.rst
- changing `pyscrip` to `pyscript`
> One more minor change to Getting Started

- .gitignore
- flexx/app/_clientcore.py
- flexx/app/_modules.py
- flexx/app/_session.py
- flexx/event/_component.py
- flexx/pyscript/stdlib.py
- tasks/docs.py
> Bunch of tweaks

- flexx/app/_app.py
- flexx/event/_property.py
- setup.py
> Value for tuple props can be passed as args to setter-action

- flexx/event/_reaction.py
- flexx/event/tests/test_reactions_dynamism.py
- flexx/ui/layouts/_hv.py
- flexx/ui/widgets/_tree.py
- Fix very specific bug in event system #406
- Fix bug that children of hvlayout could not scroll
- Improve `Tree` widget and allow items to be formatted better
> Some tweaks and bug fixes

- flexx/app/_asset.py
- flexx/ui/widgets/__init__.py
- flexx/ui/widgets/_plotly.py
- flexx/util/logging.py
- flexxamples/demos/d3_collision.py
- flexxamples/demos/plotly_gdp.py
* Add PlotlyWidget
* Add demos  for plotly and D3 
* Fix in logging
> Add plotly widget and new demos

- flexxamples/demos/chatroom.py
This fixes #480, but it's not perfect.  It eliminates the original
problem in #480.  The new, lesser problems come with the choice
between .user_done and .user_text.
.user_done is triggered whenever the widget loses focus, which happens
when the window loses focus, so if the widget has focus and then the
window loses focus, a spurious new_name message is broadcast.  This could
be supressed by tracking the name value to make sure it's new, but that
just complicates the demo and the spurious new_name message is really
really trivial.
.user_text seems like it might avoid the above, but it's fired before
the value of the widget is updated so it lags one char behind and would
complicate the demo even further to fix.
Overall this is better because it avoids the asyncio call and the
multiplying …
> fixes #480, eliminates extra _update_participants() calls

- README.md
- docs/start.rst
- flexx/app/_assetstore.py
- flexx/app/_clientcore.py
- flexx/resources/bsdf.js
- flexx/ui/_widget.py
- flexx/ui/widgets/_color.py
- flexx/ui/widgets/_dropdown.py
- flexx/ui/widgets/_label.py
- flexx/ui/widgets/_media.py
- flexx/ui/widgets/_slider.py
- flexx/ui/widgets/_tree.py
- flexxamples/howtos/control_with_keys.py
- setup.py
> Browsersupport

- flexx/ui/widgets/_dropdown.py
I saw some race conditions with the dropdown widget under specific (prob hard to reproduce) conditions. This fixes that.
> Improve dropdown internal state

- flexx/app/_component2.py
- flexx/event/_component.py
- flexx/event/_js.py
- flexx/event/both_tester.py
- flexx/ui/_widget.py
- setup.cfg
I scrolled through the generated JS of some critical (e.g. often-used) parts of the code and made a few adjustments to make things more efficient.
Also see related https://github.com/flexxui/pscript/pull/34
> Performance tweaks

- flexx/app/_app.py
Not critical, but logging was weird due to this bug.
> Small fix in App.export()

- docs/guide/patterns.rst
- docs/guide/widget_basics.rst
- docs/guide/widgets_components.rst
- docs/scripts/genexamples.py
- docs/scripts/genuiclasses.py
- flexx/app/_clientcore.py
- flexx/app/_component2.py
- flexx/app/tests/test_session.py
- flexx/event/_loop.py
- flexx/ui/__init__.py
- flexx/ui/_widget.py
- flexx/ui/pywidgets/__init__.py
- flexx/ui/pywidgets/_filebrowser.py
- flexx/ui/widgets/_label.py
- flexxamples/README.md
- flexxamples/demos/chatroom.py
- flexxamples/demos/colab_painting.py
- flexxamples/demos/monitor.py
- flexxamples/demos/splines.py
- flexxamples/howtos/cookies.py
- flexxamples/howtos/serve_data.py
- flexxamples/howtos/serve_with_asgineer.py
* Implements (and documents) a new `PyWidget` class to create high-level (compound) widgets that work in Python. This makes it easier to write Gui's that feel Pythonic.
* Add some comments to clarify the use of `getsize()`.
* Implement experimental `FileBrowserWidget`.
> Implement PyWidget (and more)

- docs/guide/pscript_modules_scope.rst
- docs/guide/widget_basics.rst
- docs/guide/widgets_components.rst
- flexxamples/howtos/scrollable.py
* Closes #522
* Closes #214
* Closes #516
* Closes #531
* Closes #518
> Improvements to docs

- docs/freeze.rst
- flexx/app/_app.py
This makes it possible to do:
```py
from flexx import flx
class Example(flx.PyWidget):
def init(self):
flx.Button(text="Hi there")
if __name__ == "__main__":
app = flx.App(Example)
app.freeze("~/Desktop/flexx_apps")
```
> Make freezing easier

- flexx/ui/widgets/_dropdown.py
> Fix unintended combobox clearing

- docs/guide/pscript_modules_scope.rst
> Fix simple typo: wherer -> where

- flexxamples/howtos/echarts_example.py
echarts is famous chart lib create by Baidu.  And donate to Apache recently. It is very popular and powerful.
https://echarts.apache.org/en/tutorial.html#Get%20Started%20with%20ECharts%20in%205%20minutes
**Add echarts example for flexx**
> Add echarts example

- docs/guide/event_system.rst
> fix typos in docs

- flexx/ui/widgets/_bokeh.py
- tasks/test.py
The layout is not really working yet. Flexx does call `resize_layout()`, but in `flexxamples\howtos\bokehdemo.py` the plot on the left does not correctly resize. I don't have the time to look into this further right now, so I'm leaving that for another person/time.
Closes #641
> Fix bokeh widget

- flexx/app/_server.py
> Workaround for long-standing bug in Tornado

- flexx/ui/_widget.py
> pywidget disposes its subwidget

- flexx/event/_component.py
> fix bug #615

- flexx/app/_tornadoserver.py
- flexx/event/_js.py
> Fix introducion of faulty JS

- flexx/app/_session.py
- flexx/event/_component.py
- flexx/event/tests/test_disposing.py
> Some measures against memory leakage

- flexxamples/howtos/leaflet.py
> Fix leaflet
